OI-2636: New guideline page
common-voice/common-voice pull request #3964
Opened 2023-03-02 08:17 UTC by moz-rotimib

2023-03-03 09:06 UTC, moz-dfeller requested changes

2023-03-03 09:06 UTC, moz-dfeller commented on web/src/components/pages/guidelines/guidelines.css
> +                            p:nth-child(2) {
same here as mentioned above

2023-03-03 09:06 UTC, moz-dfeller commented on web/src/components/pages/guidelines/guidelines.css
> +                            p:nth-child(1) {
same here as mentioned above

2023-03-03 09:06 UTC, moz-dfeller commented on web/locales/en/messages.ftl
> +reviewing-sentences-explanation-4 = If you run out of sentences to review, please help us collect more sentences!
No newline at end of file :D

2023-03-03 14:13 UTC, moz-dfeller approved these changes

2023-03-03 14:13 UTC, moz-dfeller commented on web/src/components/pages/guidelines/guidelines.css
>                                  font-size: var(--font-size-xs);
Lovely :)

2023-03-05 20:18 UTC, drzraf commented
This doesn't seem to address https://github.com/common-voice/common-voice/issues/3796 ?
Custom pronunciations rules won't be doable after such a refactor. Could this be seriously considered?

2023-03-10 12:37 UTC, drzraf commented on web/src/components/pages/guidelines/sidebar-content/voice-collection/misreadings.tsx
> +import { ExampleContent, ExampleTip } from './example-content-voice';
I couldn't figure out where will live the actual guidelines (per language) and whether we'll be able to amend them on a per language basis.

2023-03-28 03:53 UTC, drzraf commented on web/src/components/pages/guidelines/sidebar-content/voice-collection/misreadings.tsx
> +import { ExampleContent, ExampleTip } from './example-content-voice';
ping

2023-03-28 09:13 UTC, merged