fix: Correct Basque language accent typo
common-voice/common-voice pull request #4323
Opened 2024-01-17 17:22 UTC by avayyyyyyy

🚀 **Pull Request Summary:**

### Fixes #1761

Hey team! 👋

I've just addressed a long-standing issue reported in #1761. There was a small typo in the Basque language accent description, where "Araka" was mistakenly used instead of the correct term "Araba."

**Changes Made:**
- Corrected the typo in the Basque language accent associated with "Mendebalekoa."

I've tested the fix locally, and everything looks good.

🔍 **Reviewers, your input is appreciated!**

Please take a look, and if everything checks out, feel free to merge it in.
Thanks for assigning this issue to me! Excited to dive in and contribute. If there are more issues in a similar vein, I'm eager to take them on!

Cheers! 🎉

2024-01-18 09:01 UTC, jessicarose commented
Thanks so much for your quick work! So this change impacts a previous migration and would only deliver this updated accent description for people running brand new setups of the MCV project.

You'll want to write a new migration that creates a new .ts file that will sit in the same directory alongside the existing, unchanged 20211110104012-accent-tables-in-db.ts file and the other past migration files to fix this. I don't have much experience with this process myself, yet. But will be having a look at this process later today (to better update documentation around it) and should be able to offer better support around this fix later in the week, if needed!

2024-01-18 09:15 UTC, jessicarose requested changes
This change was made in the migration file from 2021 that first introduced the typo. This fix would only work for new setups of the Common Voice project. 

I would recommend reverting this file (20211110104012-accent-tables-in-db.ts) to its original state and writing a new migration that would create a new .ts file that should sit in the /model/db/migrations/ folder alongside the other migration files.

2024-02-06 10:54 UTC, jessicarose requested changes
Thank you so much and my apologies to have kept you waiting during some staff travel.

Could I request two more smallish changes?

Firstly, the filename contains the timestamp "20220124120000" which is going to show up as 2022, could you change the filename to match the current year and date? Ex 20240206120000 if we wanted it to correspond to today's date.

Also, while you've done a beautiful job with this, could I request a small change in line with best practices we're trying to enforce throughout the project?

A typo can be pretty risky with changes like these, so using the accent token instead of the long string accent name to refer to location of changes for lines 8 and 18 would reduce a lot of risk, would it be possible to have you change this to "AND accent_token = 'mendebalekoa'" instead of the longer accent_name string?

2025-03-13 13:48 UTC, moz-kathyreid commented
@avayyyyyyy Firstly a huge thank you for prepping this PR - I am doing a review of open PRs and Issues and am coming back around to see if this is still active. Would you be comfortable making the changes Jess has requested?

2025-05-28 14:08 UTC, moz-kathyreid commented
@avayyyyyyy a gentle nudge on this one - would you be comfortable making the changes Jess has requested? If not, or if I don't hear back from you, I will go ahead and make the changes.

2025-06-10 07:16 UTC, moz-dfeller commented
Since we didn't hear back, we did the fixes in #4922 . Thanks @avayyyyyyy and @moz-bozden !

2025-06-10 07:16 UTC, closed without merging