OI-2903: Update metadata viewer to sex or gender values
common-voice/common-voice pull request #4368
Opened 2024-02-08 10:17 UTC by moz-rotimib

<img width="2307" alt="Screenshot 2024-02-08 at 11 17 07" src="https://github.com/common-voice/common-voice/assets/113194143/cecc1a92-52ad-496b-89fd-b4f9d3b8a117">

2024-02-08 10:18 UTC, moz-rotimib commented
N.B. The data shown in the screenshot is mock data so it is not correct. It's just for display purposes

2024-02-13 11:55 UTC, moz-dfeller requested changes

2024-02-13 11:55 UTC, moz-dfeller commented on web/src/components/pages/datasets/metadata-viewer/types.ts
> +  transgender: number
One is missing I believe:
```suggestion
  transgender: number
  'non-binary': number
```

2024-02-14 09:19 UTC, moz-dfeller approved these changes

2024-02-14 09:27 UTC, merged